### PR TITLE
Update dblite.js

### PR DESCRIPTION
**Pull request by as3long**
fixbug when arguments.length = 2

### CODE REVIEW

**Comment by WebReflection** [comment]
can you please bump the major version too? Thanks!

**Comment by as3long** [comment]
dblite@0.7.7

my code
```javascript
function(sql) {
        var deferred = getDefer();
        var self = this;

        db.query(sql, function(err, rows) {
            if (err) {
                deferred.reject(err);
            } else {
                deferred.resolve(rows);
            }
        });

        return deferred.promise;
    }
```

**Comment by WebReflection** [comment]
I meant in this PR ... can you please update the version too? thanks :-)

**Comment by WebReflection** [comment]
?

**Pull request closed without merging**
